name: prometheus-rules-check

on:
  pull_request:
    paths:
      - "prometheus/rules/**"

jobs:
  promtool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Prometheus tools
        run: |
          sudo apt-get update
          sudo apt-get install -y prometheus

      - name: Check Prometheus rules
        run: promtool check rules prometheus/rules/parallax-dual-read.rules.yml
